pipeline {
    agent any

    stages {

        stage('Clone Code') {
            steps {
                git 'https://github.com/Shruthi786/ecommerce-app.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t ecommerce-frontend ./frontend'
            }
        }

        stage('Run Container') {
            steps {
                sh 'docker run -d -p 3000:3000 ecommerce-frontend'
            }
        }
    }
}
