pipeline {
    agent any

    environment {
        IMAGE_NAME = 'ecommerce-backend'
        CONTAINER_NAME = 'backend-container'
    }

    stages {

        stage('Clone Code') {
            steps {
                git 'https://github.com/Shruthi786/ecommerce-app.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('backend') {
                    sh 'docker build -t $IMAGE_NAME .'
                }
            }
        }

        stage('Stop Old Container') {
            steps {
                sh '''
                docker stop $CONTAINER_NAME || true
                docker rm $CONTAINER_NAME || true
                '''
            }
        }

        stage('Run Container') {
            steps {
                sh '''
                docker run -d -p 5000:5000 --name $CONTAINER_NAME $IMAGE_NAME
                '''
            }
        }
    }
}
